import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero"; // Add Hero component here
import AboutMe from "@/components/AboutMe";
import Portfolio from "@/components/Portfolio";

// Import fonts locally using Next.js
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the page
export const metadata: Metadata = {
  title: "Brodie's Portfolio",
  description: "Generated by Brodie's Next.js App",
};

// Root Layout Component
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        {/* Global Header */}
        <Header />

        {/* Main Content */}
        <main className="flex-grow">
          {/* Hero Section should be at the top */}
          <section id="hero">
            <Hero />
          </section>
          {/* About Me Section */}
          <section id="about-me">
            <AboutMe />
          </section>
          {/* Portfolio Section */}
          <section id="portfolio">
            <Portfolio />
          </section>
          {children}{" "}
          {/* This will allow other pages or components to render within the layout */}
        </main>

        {/* Global Footer */}
        <Footer />
      </body>
    </html>
  );
}
